// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package v1beta1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Conservation is database representation
type Conservation struct {
	// database unique identifier
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// creation date (timestamp without time zone)
	Created string `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	// number of sent email to keep
	Sent int64 `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	// number of unsent email to keep
	Unsent int64 `protobuf:"varint,4,opt,name=unsent,proto3" json:"unsent,omitempty"`
	// keep email content (depend of country law)
	KeepEmailContent     bool     `protobuf:"varint,5,opt,name=keep_email_content,json=keepEmailContent,proto3" json:"keep_email_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conservation) Reset()         { *m = Conservation{} }
func (m *Conservation) String() string { return proto.CompactTextString(m) }
func (*Conservation) ProtoMessage()    {}
func (*Conservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Conservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conservation.Unmarshal(m, b)
}
func (m *Conservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conservation.Marshal(b, m, deterministic)
}
func (m *Conservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conservation.Merge(m, src)
}
func (m *Conservation) XXX_Size() int {
	return xxx_messageInfo_Conservation.Size(m)
}
func (m *Conservation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conservation.DiscardUnknown(m)
}

var xxx_messageInfo_Conservation proto.InternalMessageInfo

func (m *Conservation) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Conservation) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Conservation) GetSent() int64 {
	if m != nil {
		return m.Sent
	}
	return 0
}

func (m *Conservation) GetUnsent() int64 {
	if m != nil {
		return m.Unsent
	}
	return 0
}

func (m *Conservation) GetKeepEmailContent() bool {
	if m != nil {
		return m.KeepEmailContent
	}
	return false
}

func init() {
	proto.RegisterType((*Conservation)(nil), "v1beta1.Conservation")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x18, 0x85, 0x49, 0x37, 0x37, 0x17, 0x44, 0xca, 0x2f, 0x8e, 0x52, 0xbd, 0x28, 0xbb, 0xea, 0x85,
	0x24, 0x56, 0x1f, 0x61, 0xdb, 0xc5, 0xc0, 0xab, 0x7a, 0x2d, 0x23, 0xad, 0xbf, 0x23, 0xb8, 0x25,
	0xa1, 0xfd, 0x57, 0xf0, 0xd6, 0x47, 0xd0, 0x47, 0xf3, 0x15, 0x7c, 0x10, 0x69, 0xda, 0x41, 0xbd,
	0xcb, 0x39, 0xdf, 0x49, 0x38, 0x27, 0x7c, 0xa6, 0x9c, 0x16, 0xae, 0xb2, 0x64, 0x61, 0xda, 0x64,
	0x05, 0x92, 0xca, 0xe2, 0xdb, 0x9d, 0xb5, 0xbb, 0x3d, 0x4a, 0xe5, 0xb4, 0x54, 0xc6, 0x58, 0x52,
	0xa4, 0xad, 0xa9, 0xbb, 0x58, 0x7c, 0xd3, 0x53, 0xaf, 0x8a, 0xe3, 0x9b, 0xc4, 0x83, 0xa3, 0x8f,
	0x0e, 0x2e, 0xbe, 0x18, 0xbf, 0x58, 0x5a, 0x53, 0x63, 0xd5, 0xf8, 0x4b, 0x70, 0xc9, 0x83, 0xcd,
	0x2a, 0x62, 0x09, 0x4b, 0x47, 0x79, 0xb0, 0x59, 0x41, 0xc4, 0xa7, 0x65, 0x85, 0x8a, 0xf0, 0x35,
	0x0a, 0x12, 0x96, 0xce, 0xf2, 0x93, 0x04, 0xe0, 0xe3, 0x1a, 0x0d, 0x45, 0x23, 0x9f, 0xf5, 0x67,
	0x98, 0xf3, 0xc9, 0xd1, 0x78, 0x77, 0xec, 0xdd, 0x5e, 0xc1, 0x1d, 0x87, 0x77, 0x44, 0xb7, 0xc5,
	0x83, 0xd2, 0xfb, 0x6d, 0x69, 0x0d, 0xb5, 0x99, 0xb3, 0x84, 0xa5, 0xe7, 0x79, 0xd8, 0x92, 0x75,
	0x0b, 0x96, 0x9d, 0xff, 0x40, 0xfc, 0x6a, 0xd8, 0xe9, 0x19, 0xab, 0x46, 0x97, 0x08, 0x2f, 0x3c,
	0x7c, 0xd2, 0x35, 0xfd, 0xab, 0x3b, 0x17, 0xdd, 0x3a, 0x71, 0x5a, 0x27, 0xd6, 0xed, 0xba, 0xf8,
	0x5a, 0xf4, 0x9f, 0x23, 0x86, 0xf1, 0x45, 0xf4, 0xf9, 0xf3, 0xfb, 0x1d, 0x00, 0x84, 0xb2, 0xc9,
	0x64, 0x39, 0x20, 0xf7, 0xac, 0x98, 0xf8, 0x27, 0x1e, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x60,
	0xa2, 0x77, 0x6e, 0x62, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConservationServiceClient is the client API for ConservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConservationServiceClient interface {
	// ListConservation returns a stream of List of Conservation
	ListConservation(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ConservationService_ListConservationClient, error)
}

type conservationServiceClient struct {
	cc *grpc.ClientConn
}

func NewConservationServiceClient(cc *grpc.ClientConn) ConservationServiceClient {
	return &conservationServiceClient{cc}
}

func (c *conservationServiceClient) ListConservation(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ConservationService_ListConservationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConservationService_serviceDesc.Streams[0], "/v1beta1.ConservationService/ListConservation", opts...)
	if err != nil {
		return nil, err
	}
	x := &conservationServiceListConservationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConservationService_ListConservationClient interface {
	Recv() (*Conservation, error)
	grpc.ClientStream
}

type conservationServiceListConservationClient struct {
	grpc.ClientStream
}

func (x *conservationServiceListConservationClient) Recv() (*Conservation, error) {
	m := new(Conservation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConservationServiceServer is the server API for ConservationService service.
type ConservationServiceServer interface {
	// ListConservation returns a stream of List of Conservation
	ListConservation(*empty.Empty, ConservationService_ListConservationServer) error
}

func RegisterConservationServiceServer(s *grpc.Server, srv ConservationServiceServer) {
	s.RegisterService(&_ConservationService_serviceDesc, srv)
}

func _ConservationService_ListConservation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConservationServiceServer).ListConservation(m, &conservationServiceListConservationServer{stream})
}

type ConservationService_ListConservationServer interface {
	Send(*Conservation) error
	grpc.ServerStream
}

type conservationServiceListConservationServer struct {
	grpc.ServerStream
}

func (x *conservationServiceListConservationServer) Send(m *Conservation) error {
	return x.ServerStream.SendMsg(m)
}

var _ConservationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1beta1.ConservationService",
	HandlerType: (*ConservationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListConservation",
			Handler:       _ConservationService_ListConservation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
