// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

/*
Package mongopb is a generated protocol buffer package.

It is generated from these files:
	proto/service.proto

It has these top-level messages:
	MailResponse
	MailRequest
*/
package mongopb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MailResponse struct {
	From        string   `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To          []string `protobuf:"bytes,2,rep,name=to" json:"to,omitempty"`
	Object      string   `protobuf:"bytes,3,opt,name=object" json:"object,omitempty"`
	Content     string   `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	Hash        string   `protobuf:"bytes,5,opt,name=hash" json:"hash,omitempty"`
	Timestamp   string   `protobuf:"bytes,6,opt,name=timestamp" json:"timestamp,omitempty"`
	Environment string   `protobuf:"bytes,7,opt,name=environment" json:"environment,omitempty"`
	Entity      string   `protobuf:"bytes,8,opt,name=entity" json:"entity,omitempty"`
}

func (m *MailResponse) Reset()                    { *m = MailResponse{} }
func (m *MailResponse) String() string            { return proto.CompactTextString(m) }
func (*MailResponse) ProtoMessage()               {}
func (*MailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MailResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MailResponse) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MailResponse) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *MailResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MailResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *MailResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *MailResponse) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *MailResponse) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

type MailRequest struct {
	Environment string `protobuf:"bytes,1,opt,name=environment" json:"environment,omitempty"`
	Entity      string `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
}

func (m *MailRequest) Reset()                    { *m = MailRequest{} }
func (m *MailRequest) String() string            { return proto.CompactTextString(m) }
func (*MailRequest) ProtoMessage()               {}
func (*MailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MailRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *MailRequest) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func init() {
	proto.RegisterType((*MailResponse)(nil), "mongopb.MailResponse")
	proto.RegisterType((*MailRequest)(nil), "mongopb.MailRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mail service

type MailClient interface {
	ReadMails(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (Mail_ReadMailsClient, error)
}

type mailClient struct {
	cc *grpc.ClientConn
}

func NewMailClient(cc *grpc.ClientConn) MailClient {
	return &mailClient{cc}
}

func (c *mailClient) ReadMails(ctx context.Context, in *MailRequest, opts ...grpc.CallOption) (Mail_ReadMailsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Mail_serviceDesc.Streams[0], c.cc, "/mongopb.Mail/ReadMails", opts...)
	if err != nil {
		return nil, err
	}
	x := &mailReadMailsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Mail_ReadMailsClient interface {
	Recv() (*MailResponse, error)
	grpc.ClientStream
}

type mailReadMailsClient struct {
	grpc.ClientStream
}

func (x *mailReadMailsClient) Recv() (*MailResponse, error) {
	m := new(MailResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Mail service

type MailServer interface {
	ReadMails(*MailRequest, Mail_ReadMailsServer) error
}

func RegisterMailServer(s *grpc.Server, srv MailServer) {
	s.RegisterService(&_Mail_serviceDesc, srv)
}

func _Mail_ReadMails_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MailServer).ReadMails(m, &mailReadMailsServer{stream})
}

type Mail_ReadMailsServer interface {
	Send(*MailResponse) error
	grpc.ServerStream
}

type mailReadMailsServer struct {
	grpc.ServerStream
}

func (x *mailReadMailsServer) Send(m *MailResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Mail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mongopb.Mail",
	HandlerType: (*MailServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadMails",
			Handler:       _Mail_ReadMails_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0xe5, 0x34, 0x24, 0xe4, 0x8a, 0x18, 0x8e, 0x0f, 0x59, 0x88, 0x21, 0xea, 0xd4, 0x29,
	0x20, 0xd8, 0x18, 0x59, 0x98, 0x58, 0xf2, 0x06, 0x49, 0x38, 0xa8, 0x11, 0xf6, 0x85, 0xf8, 0xa8,
	0xc4, 0x5b, 0xf2, 0x48, 0xc8, 0x76, 0x11, 0x51, 0x87, 0x6e, 0xff, 0x8f, 0xe8, 0x97, 0xf3, 0x1f,
	0xce, 0xc6, 0x89, 0x85, 0x6f, 0x3c, 0x4d, 0x5b, 0x33, 0x50, 0x13, 0x1d, 0x96, 0x96, 0xdd, 0x1b,
	0x8f, 0xfd, 0xea, 0x47, 0xc1, 0xc9, 0x73, 0x67, 0x3e, 0x5a, 0xf2, 0x23, 0x3b, 0x4f, 0x88, 0x90,
	0xbf, 0x4e, 0x6c, 0xb5, 0xaa, 0xd5, 0xba, 0x6a, 0xa3, 0xc6, 0x53, 0xc8, 0x84, 0x75, 0x56, 0x2f,
	0xd6, 0x55, 0x9b, 0x09, 0xe3, 0x25, 0x14, 0xdc, 0xbf, 0xd3, 0x20, 0x7a, 0x11, 0xbf, 0xda, 0x39,
	0xd4, 0x50, 0x0e, 0xec, 0x84, 0x9c, 0xe8, 0x3c, 0x16, 0x7f, 0x36, 0x50, 0x37, 0x9d, 0xdf, 0xe8,
	0xa3, 0x44, 0x0d, 0x1a, 0xaf, 0xa1, 0x12, 0x63, 0xc9, 0x4b, 0x67, 0x47, 0x5d, 0xc4, 0xe2, 0x3f,
	0xc0, 0x1a, 0x96, 0xe4, 0xb6, 0x66, 0x62, 0x67, 0x03, 0xaf, 0x8c, 0xfd, 0x3c, 0x0a, 0x57, 0x90,
	0x13, 0x23, 0xdf, 0xfa, 0x38, 0x5d, 0x91, 0xdc, 0xea, 0x09, 0x96, 0xe9, 0x45, 0x9f, 0x5f, 0xe4,
	0x65, 0x1f, 0xa4, 0x0e, 0x81, 0xb2, 0x39, 0xe8, 0xee, 0x11, 0xf2, 0x00, 0xc2, 0x07, 0xa8, 0x5a,
	0xea, 0x5e, 0x82, 0xf6, 0x78, 0xde, 0xec, 0xa6, 0x6b, 0x66, 0x3f, 0xb9, 0xba, 0xd8, 0x4b, 0xd3,
	0x98, 0xb7, 0xaa, 0x2f, 0xe2, 0xde, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xb1, 0x55,
	0xd2, 0x86, 0x01, 0x00, 0x00,
}
